databases:
  server93Api:
    host: 192.168.1.93
    user: 'test'
    password: '123456'
    name: 'dataapi'
    pool_size: 20          # 连接池大小
    max_overflow: 20       # 连接池溢出数
  joinquant:
    host: 192.168.1.93
    user: 'test'
    password: '123456'
    name: 'joinquant'
    pool_size: 20          # 连接池大小
    max_overflow: 20       # 连接池溢出数
  mysql18:
    host: 192.168.1.18
    user: 'root'
    password: '123456'
    name: 'userdb'
    pool_size: 20          # 连接池大小
    max_overflow: 20       # 连接池溢出数
